CREATE DATABASE IF NOT EXISTS prova_suficiencia_db;
USE prova_suficiencia_db;

CREATE TABLE IF NOT EXISTS USUARIOS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Telefone VARCHAR(20),
    Email VARCHAR(100) NOT NULL UNIQUE,
    Senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Preco DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS COMANDAS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Usuarios_id INT NOT NULL,
    FOREIGN KEY (Usuarios_id) REFERENCES USUARIOS(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMANDA_PRODUTO (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ComandaId INT NOT NULL,
    ProdutoId INT NOT NULL,
    FOREIGN KEY (ComandaId) REFERENCES COMANDAS(Id) ON DELETE CASCADE,
    FOREIGN KEY (ProdutoId) REFERENCES PRODUTOS(Id) ON DELETE CASCADE,
    UNIQUE (ComandaId, ProdutoId)
);